= File Format
:sectnums:

Byte order is little endian and the character encoding of file names seems to be
ASCII (or ISO-8859-1/UTF-8 that coincidentally only uses ASCII compatiple
characters).

Offsets and sizes seem to be 64bit or at least unsigned 32bit integers. If
interpreted as 32bit integers all sizes (except the size of file names) and offsets
are followed by another 32bit integer of the value 0, which makes me guess these
are 64bit values. Also some values exceed the range of signed 32bit integers, so
they have to be at least unsigned 32bit integers.

This information was reverse engineered from the Elemental
https://wiki.unrealengine.com/Linux_Demos[Demo] for Linux (which contains a 2.5
GB .pak file), the https://www.techpowerup.com/download/unreal-engine-4-five-tech-demos/[Unreal Engine 4 - Five Tech Demos],
version 7 was reverse engineered from the https://store.steampowered.com/app/813630/Supraland/[Supraland Demo],
and the Conan Exiles variant was reverse egineered from the
https://steamcommunity.com/sharedfiles/filedetails/?id=1765361591[SandstormFix_EXP workshop item].
Reverse engineering was done by poking around the pak files with a hex editor,
no kind of decompilation was done by me.

Versions >= 8 where reversed from an empty unreal engine project.

.Basic layout
* Data Records
* Index
** Index Header
** Index Records
* Footer

In order to parse a file you need to read the footer first. The footer contains
an offset pointer to the start of the index records. The index records then
contain offset pointers to the data records.

:leveloffset: +1
include::file-format/record.adoc[]
include::file-format/compression-block.adoc[]
include::file-format/data-record.adoc[]
include::file-format/index-record.adoc[]
include::file-format/index.adoc[]
include::file-format/footer.adoc[]
:leveloffset: -1
